const bgStylePokemonType = {
    'normal': 'bg-gradient-to-b from-normal-txt to-white',
    'fighting': 'bg-gradient-to-b from-fighting-txt to-white',
    'flying': 'bg-gradient-to-b from-flying-txt to-white',
    'poison': 'bg-gradient-to-b from-poison-txt to-white',
    'ground': 'bg-gradient-to-b from-ground-txt to-white',
    'rock': 'bg-gradient-to-b from-rock-txt to-white',
    'bug': 'bg-gradient-to-b from-bug-txt to-white',
    'ghost': 'bg-gradient-to-b from-ghost-txt to-white',
    'steel': 'bg-gradient-to-b from-steel-txt to-white',
    'fire': 'bg-gradient-to-b from-fire-txt to-white',
    'water': 'bg-gradient-to-b from-water-txt to-white',
    'grass': 'bg-gradient-to-b from-grass-txt to-white',
    'electric': 'bg-gradient-to-b from-electric-txt to-white',
    'psychic': 'bg-gradient-to-b from-psychic-txt to-white',
    'ice': 'bg-gradient-to-b from-ice-txt to-white',
    'dragon': 'bg-gradient-to-b from-dragon-txt to-white',
    'dark': 'bg-gradient-to-b from-dark-txt to-white',
    'fairy': 'bg-gradient-to-b from-fairy-txt to-white',
    'unknown': 'bg-gradient-to-b from-unknown-txt to-white',
    'shadow': 'bg-gradient-to-b from-shadow-txt to-white'
}

const borderStyledPokemonByPokemonType = {
    'normal': 'border-[4px] border-normal-txt',
    'fighting': 'border-[4px] border-fighting-txt',
    'flying': 'border-[4px] border-flying-txt',
    'poison': 'border-[4px] border-poison-txt',
    'ground': 'border-[4px] border-ground-txt',
    'rock': 'border-[4px] border-rock-txt',
    'bug': 'border-[4px] border-bug-txt',
    'ghost': 'border-[4px] border-ghost-txt',
    'steel': 'border-[4px] border-steel-txt',
    'fire': 'border-[4px] border-fire-txt',
    'water': 'border-[4px] border-water-txt',
    'grass': 'border-[4px] border-grass-txt',
    'electric': 'border-[4px] border-electric-txt',
    'psychic': 'border-[4px] border-psychic-txt',
    'ice': 'border-[4px] border-ice-txt',
    'dragon': 'border-[4px] border-dragon-txt',
    'dark': 'border-[4px] border-dark-txt',
    'fairy': 'border-[4px] border-fairy-txt',
    'unknown': "border-[4px] border-unknown-txt",
    'shadow': "border-[4px] border-shadow-txt",
}

const textColorByType = {
    'normal': 'text-normal-txt',
    'fighting': 'text-fighting-txt',
    'flying': 'text-flying-txt',
    'poison': 'text-poison-txt',
    'ground': 'text-ground-txt',
    'rock': 'text-rock-txt',
    'bug': 'text-bug-txt',
    'ghost': 'text-ghost-txt',
    'steel': 'text-steel-txt',
    'fire': 'text-fire-txt',
    'water': 'text-water-txt',
    'grass': 'text-grass-txt',
    'electric': 'text-electric-txt',
    'psychic': 'text-psychic-txt',
    'ice': 'text-ice-txt',
    'dragon': 'text-dragon-txt',
    'dark': 'text-dark-txt',
    'fairy': 'text-fairy-txt',
    'unknown': "text-unknown-txt",
    'shadow': "text-shadow-txt",
}

export {
    bgStylePokemonType,
    borderStyledPokemonByPokemonType,
    textColorByType
}