const bgStylePokemonType = {
  normal: "bg-gradient-to-b from-normal-txt to-white",
  fighting: "bg-gradient-to-b from-fighting-txt to-white",
  flying: "bg-gradient-to-b from-flying-txt to-white",
  poison: "bg-gradient-to-b from-poison-txt to-white",
  ground: "bg-gradient-to-b from-ground-txt to-white",
  rock: "bg-gradient-to-b from-rock-txt to-white",
  bug: "bg-gradient-to-b from-bug-txt to-white",
  ghost: "bg-gradient-to-b from-ghost-txt to-white",
  steel: "bg-gradient-to-b from-steel-txt to-white",
  fire: "bg-gradient-to-b from-fire-txt to-white",
  water: "bg-gradient-to-b from-water-txt to-white",
  grass: "bg-gradient-to-b from-grass-txt to-white",
  electric: "bg-gradient-to-b from-electric-txt to-white",
  psychic: "bg-gradient-to-b from-psychic-txt to-white",
  ice: "bg-gradient-to-b from-ice-txt to-white",
  dragon: "bg-gradient-to-b from-dragon-txt to-white",
  dark: "bg-gradient-to-b from-dark-txt to-white",
  fairy: "bg-gradient-to-b from-fairy-txt to-white",
  unknown: "bg-gradient-to-b from-unknown-txt to-white",
  shadow: "bg-gradient-to-b from-shadow-txt to-white",
};
const bgStatsPokemonType = {
  normal: "bg-gradient-to-r from-normal-bg to-bg-normal-txt",
  fighting: "bg-gradient-to-r from-fighting-bg to-bg-fighting-txt",
  flying: "bg-gradient-to-r from-flying-bg to-bg-flying-txt",
  poison: "bg-gradient-to-r from-poison-bg to-bg-poison-txt",
  ground: "bg-gradient-to-r from-ground-bg to-bg-ground-txt",
  rock: "bg-gradient-to-r from-rock-bg to-bg-rock-txt",
  bug: "bg-gradient-to-r from-bug-bg to-bg-bug-txt",
  ghost: "bg-gradient-to-r from-ghost-bg to-bg-ghost-txt",
  steel: "bg-gradient-to-r from-steel-bg to-bg-steel-txt",
  fire: "bg-gradient-to-r from-fire-bg to-bg-fire-txt",
  water: "bg-gradient-to-r from-water-bg to-bg-water-txt",
  grass: "bg-gradient-to-r from-grass-bg to-bg-grass-txt",
  electric: "bg-gradient-to-r from-electric-bg to-bg-electric-txt",
  psychic: "bg-gradient-to-r from-psychic-bg to-bg-psychic-txt",
  ice: "bg-gradient-to-r from-ice-bg to-bg-ice-txt",
  dragon: "bg-gradient-to-r from-dragon-bg to-bg-dragon-txt",
  dark: "bg-gradient-to-r from-dark-bg to-bg-dark-txt",
  fairy: "bg-gradient-to-r from-fairy-bg to-bg-fairy-txt",
  unknown: "bg-gradient-to-r from-unknown-bg to-bg-unknown-txt",
  shadow: "bg-gradient-to-r from-shadow-bg to-bg-shadow-txt",
};

const borderStyledPokemonByPokemonType = {
  normal: "border-[4px] border-normal-txt",
  fighting: "border-[4px] border-fighting-txt",
  flying: "border-[4px] border-flying-txt",
  poison: "border-[4px] border-poison-txt",
  ground: "border-[4px] border-ground-txt",
  rock: "border-[4px] border-rock-txt",
  bug: "border-[4px] border-bug-txt",
  ghost: "border-[4px] border-ghost-txt",
  steel: "border-[4px] border-steel-txt",
  fire: "border-[4px] border-fire-txt",
  water: "border-[4px] border-water-txt",
  grass: "border-[4px] border-grass-txt",
  electric: "border-[4px] border-electric-txt",
  psychic: "border-[4px] border-psychic-txt",
  ice: "border-[4px] border-ice-txt",
  dragon: "border-[4px] border-dragon-txt",
  dark: "border-[4px] border-dark-txt",
  fairy: "border-[4px] border-fairy-txt",
  unknown: "border-[4px] border-unknown-txt",
  shadow: "border-[4px] border-shadow-txt",
};

const textColorByType = {
  normal: "text-normal-txt",
  fighting: "text-fighting-txt",
  flying: "text-flying-txt",
  poison: "text-poison-txt",
  ground: "text-ground-txt",
  rock: "text-rock-txt",
  bug: "text-bug-txt",
  ghost: "text-ghost-txt",
  steel: "text-steel-txt",
  fire: "text-fire-txt",
  water: "text-water-txt",
  grass: "text-grass-txt",
  electric: "text-electric-txt",
  psychic: "text-psychic-txt",
  ice: "text-ice-txt",
  dragon: "text-dragon-txt",
  dark: "text-dark-txt",
  fairy: "text-fairy-txt",
  unknown: "text-unknown-txt",
  shadow: "text-shadow-txt",
};

const bgUnderColorByType = {
  normal: "bg-normal-txt",
  fighting: "bg-fighting-txt",
  flying: "bg-flying-txt",
  poison: "bg-poison-txt",
  ground: "bg-ground-txt",
  rock: "bg-rock-txt",
  bug: "bg-bug-txt",
  ghost: "bg-ghost-txt",
  steel: "bg-steel-txt",
  fire: "bg-fire-txt",
  water: "bg-water-txt",
  grass: "bg-grass-txt",
  electric: "bg-electric-txt",
  psychic: "bg-psychic-txt",
  ice: "bg-ice-txt",
  dragon: "bg-dragon-txt",
  dark: "bg-dark-txt",
  fairy: "bg-fairy-txt",
  unknown: "bg-unknown-txt",
  shadow: "bg-shadow-txt",
};
const bgOverColorByType = {
  normal: "bg-normal-bg",
  fighting: "bg-fighting-bg",
  flying: "bg-flying-bg",
  poison: "bg-poison-bg",
  ground: "bg-ground-bg",
  rock: "bg-rock-bg",
  bug: "bg-bug-bg",
  ghost: "bg-ghost-bg",
  steel: "bg-steel-bg",
  fire: "bg-fire-bg",
  water: "bg-water-bg",
  grass: "bg-grass-bg",
  electric: "bg-electric-bg",
  psychic: "bg-psychic-bg",
  ice: "bg-ice-bg",
  dragon: "bg-dragon-bg",
  dark: "bg-dark-bg",
  fairy: "bg-fairy-bg",
  unknown: "bg-unknown-bg",
  shadow: "bg-shadow-bg",
};

export {
  bgStylePokemonType,
  borderStyledPokemonByPokemonType,
  textColorByType,
  bgUnderColorByType,
  bgOverColorByType,
  bgStatsPokemonType
};
